#ifndef ACEROLA_WATCH_H
#define ACEROLA_WATCH_H

#include <Watchy.h>
#include "faces/_faces.h"
#include "fonts.h"

class AcerolaWatch : public Watchy {
  public:
    AcerolaWatch();
    void drawWatchFace();
    void Face1();
    void Face2();
    void Face3();
    void Face4();
    void Face5();
    void Face6();
    void Face7();
    void Face8();
    void Face9();
    void Face10();
    void Face11();
    void Face12();
    void Face13();
    void Face14();
    void Face15();
    void Face16();
    void Face17();
    void Face18();
    void Face19();
    void Face20();
    void Face21();
    void Face22();
    void Face23();
    void Face24();
    void Face25();
    void Face26();
    void Face27();
    void Face28();
    void Face29();
    void Face30();
    void Face31();
    void Face32();
    void Face33();
    void Face34();
    void Face35();
    void Face36();
    void Face37();
    void Face38();
    void Face39();
    void Face40();
    void Face41();
    void Face42();
    void Face43();
    void Face44();
    void Face45();
    void Face46();
    void Face47();
    void Face48();
    void Face49();
    void Face50();
    void Face51();
    void Face52();
    void Face53();
    void Face54();
    void Face55();
    void Face56();
    void Face57();
    void Face58();
    void Face59();
    void Face60();
    void Face61();
    void Face62();
    void Face63();
    void Face64();
    void Face65();
    void Face66();
    void Face67();
    void Face68();
    void Face69();
    void Face70();
    void Face71();
    void Face72();
    void Face73();
    void Face74();
    void Face75();
};

#endif
