#ifndef FONTS_H
#define FONTS_H

#include "fonts/CC_YadaYadaYada18pt7b.h"
#include "fonts/CC_YadaYadaYada12pt7b.h"
#include "fonts/CC_YadaYadaYada9pt7b.h"
#include "fonts/CC_YadaYadaYada6pt7b.h"
#include "fonts/Manti_Sans_Fixed_Demo20pt7b.h"
#include "fonts/Manti_Sans_Fixed_Demo18pt7b.h"
#include "fonts/Manti_Sans_Fixed_Demo10pt7b.h"
#include "fonts/BAR10pt7b.h"
#include "fonts/BAR20pt7b.h"
#include "fonts/Lumber_Regular9pt7b.h"
#include "fonts/Lumber_Regular10pt7b.h"
#include "fonts/Lumber_Regular12pt7b.h"
#include "fonts/Lumber_Regular20pt7b.h"
#include "fonts/Compacta_Bold_Plain_Regular15pt7b.h"
#include "fonts/Compacta_Bold_Plain_Regular20pt7b.h"
#include "fonts/Compacta_Bold_Plain_Regular25pt7b.h"
#include "fonts/Compacta_Bold_Plain_Regular30pt7b.h"
#include "fonts/Devasia_Bold32pt7b.h"
#include "fonts/Devasia_Bold28pt7b.h"
#include "fonts/Devasia_Bold18pt7b.h"
#include "fonts/amsterdam30pt7b.h"
#include "fonts/VT323_Regular20pt7b.h"
#include "fonts/VT323_Regular18pt7b.h"
#include "fonts/VT323_Regular12pt7b.h"
#include "fonts/cmuntx24pt7b.h"
#include "fonts/cmuntx18pt7b.h"
#include "fonts/cmuntx14pt7b.h"
#include "fonts/cmuntx10pt7b.h"

#endif